// COMPETITIONS
export const COMPETITIONS_REQUEST = 'COMPETITIONS_REQUEST'
export const COMPETITIONS_SUCCESS = 'COMPETITIONS_SUCCESS'
export const COMPETITIONS_FAILURE = 'COMPETITIONS_FAILURE'

// MAKE FAVOURITE COMPETITIONS
export const FAV_COMPETITIONS_REQUEST = 'FAV_COMPETITIONS_REQUEST'
export const FAV_COMPETITIONS_SUCCESS = 'FAV_COMPETITIONS_SUCCESS'
export const FAV_COMPETITIONS_FAILURE = 'FAV_COMPETITIONS_FAILURE'