// GET TEAMS 
export const GET_TEAMS_REQUEST = 'GET_TEAMS_REQUEST'
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS'
export const GET_TEAMS_FAILURE = 'GET_TEAMS_FAILURE'

// GET TEAMS DETAILS
export const TEAM_DETAILS_REQUEST = 'TEAM_DETAILS_REQUEST'
export const TEAM_DETAILS_SUCCESS = 'TEAM_DETAILS_SUCCESS'
export const TEAM_DETAILS_FAILURE = 'TEAM_DETAILS_FAILURE'